---ROLL OUT
ALTER TABLE TBL_DIAS_TRABAJADOS
ADD ID_PERFIL NUMERIC(18,0)

---ROLL BACK
ALTER TABLE TBL_DIAS_TRABAJADOS
DROP COLUMN ID_PERFIL 

---ROLL OUT
CREATE TABLE [dbo].[TBL_SISTEMA](
	[ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL Primary key,
	[PARAMETRO] [varchar](255) NULL,
	[VALOR] [varchar](255) NULL
)

---ROLL BACK
DROP TABLE [dbo].[TBL_SISTEMA]
