//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColinaApplication.Data.Conexion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBLaColina : DbContext
    {
        public DBLaColina()
            : base("name=DBLaColina")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBL_CATEGORIAS> TBL_CATEGORIAS { get; set; }
        public DbSet<TBL_PRODUCTOS> TBL_PRODUCTOS { get; set; }
        public DbSet<TBL_PRODUCTOS_SOLICITUD> TBL_PRODUCTOS_SOLICITUD { get; set; }
        public DbSet<TBL_USUARIOS> TBL_USUARIOS { get; set; }
        public DbSet<TBL_IMPUESTOS> TBL_IMPUESTOS { get; set; }
        public DbSet<TBL_MASTER_MESAS> TBL_MASTER_MESAS { get; set; }
        public DbSet<TBL_CIERRES> TBL_CIERRES { get; set; }
        public DbSet<TBL_PERFIL> TBL_PERFIL { get; set; }
        public DbSet<TBL_DIAS_TRABAJADOS> TBL_DIAS_TRABAJADOS { get; set; }
        public DbSet<TBL_NOMINA> TBL_NOMINA { get; set; }
        public DbSet<TBL_SOLICITUD> TBL_SOLICITUD { get; set; }
    }
}
