//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColinaApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTOS_SOLICITUD
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<decimal> ID_SOLICITUD { get; set; }
        public Nullable<decimal> ID_SUBPRODUCTO { get; set; }
        public Nullable<decimal> ID_MESERO { get; set; }
        public Nullable<decimal> PRECIO_PRODUCTO { get; set; }
        public Nullable<decimal> PRECIO_FINAL { get; set; }
        public string ESTADO_PRODUCTOS { get; set; }
    }
}
