//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColinaApplication.Data.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DIAS_TRABAJADOS
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_USUARIO_NOMINA { get; set; }
        public Nullable<System.DateTime> FECHA_TRABAJADO { get; set; }
        public Nullable<decimal> PROPINAS { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
    }
}
