//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColinaApplication.Data.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NOMINA
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_USUARIO_SISTEMA { get; set; }
        public Nullable<decimal> ID_PERFIL { get; set; }
        public Nullable<decimal> CEDULA { get; set; }
        public string NOMBRE { get; set; }
        public string CARGO { get; set; }
        public Nullable<decimal> SUELDO_DIARIO { get; set; }
        public Nullable<decimal> DIAS_TRABAJADOS { get; set; }
        public Nullable<decimal> PROPINAS { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string DIRECCION_RESIDENCIA { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> TOTAL_PAGAR { get; set; }
    }
}
