//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColinaApplication.Data.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRECIOS_SUBPRODUCTOS
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_SUBPRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PRECIO_INDIVIDUAL { get; set; }
        public Nullable<decimal> CANTIDAD_PORCION { get; set; }
        public Nullable<decimal> VALOR_MEDIDA { get; set; }
    }
}
