//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColinaApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTOS_LOG
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_PRINCIPAL { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public string NOMBRE_SUBPRODUCTO { get; set; }
        public string PRECIO_UNITARIO { get; set; }
        public Nullable<decimal> CANTIDAD_EXISTENCIA { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
